version: '3'

services:
  test:
    image: sargilo:${DJANGO}
    build:
      dockerfile: sargilo/tests/${DJANGO}_test_project/Dockerfile
      context: .

    working_dir: /app/sargilo/tests/${DJANGO}_test_project
    volumes:
      - .:/app

    user: "1000:1000"
